### PR TITLE
plumbing: Use ReadBytes() rather than ReadSlice()

### PR DESCRIPTION
**Pull request by lupine**
Fixes https://github.com/src-d/go-git/issues/249

### CODE REVIEW

**Comment by mcuadros** [comment]
Can you provide a test for it? To avoid duplicate this bug again? A slice with more than 4096 chars without a newline should be enough for test the issue. Thanks!

**Comment by hansrodtang** [comment]
I am not sure what the original reason for using `ReadSlice()`, but `ReadBytes()` makes a copy of the data read, so won't this change put more pressure on the GC?

Or is this deemed not an issue? I haven't looked into how much the memory usage increases with the change, just a quick observation that might be unimportant.

**Comment by lupine** [comment]
@mcuadros the existing test suite seems to rely  heavily on a set of external fixtures: github.com/src-d/go-git-fixtures

Do I issue a PR against that repo to get a fixture added? 

@hansrodtang it will result in an extra copy per line but we're already doing at least one copy per line, so I don't think it's a major issue - we're not changing the scaling behaviour fundamentally by this change.

**Comment by lupine** [comment]
Ah, never mind, I found a way to add tests without changing fixtures. Wdyt @mcuadros ? I verified that the tests fail without the fix.

**Comment by lupine** [comment]
If accepted, will this fix end up in `gopkg.in/src-d/go-git.v4` automatically? Or is there a process / timeline for getting it added?

**Comment by mcuadros** [comment]
@hansrodtang thanks for pointing the extra memory usage, once we have a stable API, we will take care of the performance reviewing the code base to improve this from the root.

@lupine yep, I need update the v4 branch, but I will do it ASAP.

**Comment by mcuadros** [comment]
@lupine v4 has been updated, https://github.com/src-d/go-git/tree/v4. 
BTW if you don't mind... may I know for what are you using go-git?

**Comment by lupine** [comment]
@mcuadros https://gitlab.com/gitlab-org/es-git-go at the moment. i'm starting to see uses for it elsewhere too, though :D

**Comment by lupine** [comment]
Thanks so much for the merge!

**Pull request merged**
