### PR TITLE
Teach ResolveRevision how to look up annotated tags

### PR DESCRIPTION
**Pull request by novas0x2a**
This should address #772. The existing tests aren't broken by this, but I'm not quite sure how to add an annotated tag to the fixtures to add a new test for this.

### CODE REVIEW

**Comment by mcuadros** [comment]
Well, the tests are passing. Means that you managed to solve it, or is that were failing in your local environment?

Can you cover this change by a test?

**Comment by novas0x2a** [comment]
Any updates on this or on https://github.com/src-d/go-git-fixtures/issues/1 , which this PR is kind of blocked on?

**Comment by novas0x2a** [comment]
@mcuadros?

**Comment by mcuadros** [comment]
Sorry for the late response, the fixtures can't be regenerated are immutable, if you want to cover a new case that can't be done using any of the current fixtures, you need to submit a PR with the new fixture. 

The dotgit folders are a tarball of the `.git` and the name is the sha1 of the tar file. The packfiles are just the packfile.

The fixtures are based on https://github.com/git-fixtures/

**Pull request merged**
