### PR TITLE
transport: http push

### LINKED ISSUE #406: Push with HTTPS : receive-pack not supported yet
Hello,
I'm trying to use go-git to clone/add/commit/push with HTTPS (not ssh).
I have no problem with the clone/add/commit but when i try to push i get the following error : **error: receive-pack not supported yet**

This is the pseudo-code i use : 

```
import (
	"gopkg.in/src-d/go-git.v4"
	"gopkg.in/src-d/go-git.v4/plumbing/object"
	githttp "gopkg.in/src-d/go-git.v4/plumbing/transport/http"
)

httpAuth := githttp.NewBasicAuth("user", "password")
r, err := git.PlainClone(tmpGitDir, false, &git.CloneOptions{
	URL:      "https://gitlab/test.git",
	Progress: os.Stdout,
	Auth:     httpAuth,
})
CheckIfError(err)

w, err := r.Worktree()
CheckIfError(err)

_, err = w.Add("file.txt")
CheckIfError(err)

_, err := w.Commit("example go-git commit", &git.CommitOptions{
	Author: &object.Signature{
		Name:  "User test",
		Email: "toto@coco.com",
		When:  time.Now(),
	},
})
CheckIfError(err)

log.Print("we push")
err = r.Push(&git.PushOptions{Auth: httpAuth})
CheckIfError(err)
```

Everything works fine except the push.
If i don't use the httpAuth on the push i get the same error.
If i try the command "git http-push ..." directly from the bash, it works fine.

Any idea ?
Thanks ;)

### PR DESCRIPTION
**Pull request by ajnavarro**
Fix #406

### CODE REVIEW

**Comment by ajnavarro** [comment]
I'm having problems to make the CGI server works.

**Comment by smola** [comment]
Damn CGI :wink:

**Comment by ajnavarro** [comment]
The CGI server now is working. The only error that I'm having now, is `auth required`

**Comment by ajnavarro** [comment]
I think that I found the problem: https://git-scm.com/docs/git-http-backend#_services

**Comment by ajnavarro** [comment]
@mcuadros ping

**Pull request merged**
