### PR TITLE
on demand http auth example

### PR DESCRIPTION
**Pull request by alcortesm**
The goal of the pseudo-code at #350 (comment) can be improved with this example.

### CODE REVIEW

**Comment by alcortesm** [comment]
umm, tests fails, any idea on how to write this example so it doesn't fail?

**Comment by smola** [comment]
@alcortesm You'd need to get credentials from an environment variable, skip the tests if the variable is not defined and add credentials to Travis using the secrets API.

**Comment by jdoklovic** [comment]
This gets me closer in terms of http auth, however, I think there should be a high-level "helper" to handle different url schemes.  e.g.:
```go
func AuthMethodForURL(url string) transport.AuthMethod {
    if IsSSH(url) {
        // 1:scheme, 2:user, 3:host, 4:path
        m := scpLikeUrlRegExp.FindStringSubmatch(url)
        a, _ := ssh.NewSSHAgentAuth(m[2])
        return a
    }
    ba := http.NewBasicAuth("", "")
    return ba
}
opts := git.CloneOptions{
        URL:      gitURL,
        Auth:    AuthMethodForURL(gitURL),
        Progress: os.Stdout,
}
err := git.Clone(directory, opts)

if err != nil {
    if err == transport.ErrAuthorizationRequired {
        Warning("Authentication required")
        Warning("Removing previously created directory")
        os.RemoveAll(directory)
        Warning("Trying again with some fake auth information")

        // ask for authentication credentials and try again...
        opts.Auth = http.NewBasicAuth("foo", "bar")
        _, err = git.PlainClone(directory, false, &opts)
        CheckIfError(err)
    } else {
        CheckIfError(err)
    }
}
```

Just saying, seems like this is going to be a common thing to do since git can handle multiple url schemes.
I might even consider putting a "fallback" on AuthMethod that gets called when there's an AuthRequired error so you could chain together different auth methods easily rather than having every consumer write this error handling code.

**Comment by mcuadros** [comment]
@jdoklovic If what you want is extract an BasicAuth from the endpoint, this is already implemented. 
https://github.com/src-d/go-git/blob/master/plumbing/transport/http/upload_pack.go#L23-L27

```
PlainClone("http://user:pass@github.com/user/repository.git", ...) 
```

**Comment by smola** [comment]
Actually, having a way to pass a default auth for any kind of URL could make sense. A helper to get the protocol out of a URL could indeed make sense, since this functionality already exists in the `transport` package but it's not expose to the public.

We could consider exposing certain functionality that makes implementing this easier.

**Comment by smola** [comment]
I created a PR for a `clone` cli command that could subsume this example, but including all auth protocols: https://github.com/src-d/go-git/pull/399

**Comment by alcortesm** [comment]
Awesome!

**Pull request closed without merging**
