### PR TITLE
Add basic host key verification

### PR DESCRIPTION
**Pull request by adampointer**
Refs #328 

Very basic implementation of host key verification.

### CODE REVIEW

**Comment by smola** [comment]
From https://github.com/src-d/go-git/issues/328#issuecomment-292168389

Your solutions seems the right one to me. You could add the following in a PR:

* Apply the same defaults to `ssh.Password` auth method.
* Document in PublicKeys/Password godoc that they use known_hosts.
* Make `clientConfig()` public in `ssh.AuthMethod`.

This way users would be able to easily override this behavior (for example, to use an in-memory map for their own custom known hosts).

**Comment by Xfennec** [comment]
It's maybe obvious, but while trying this PR, I discovered in `man 8 sshd` that `known_hosts` format can be a bit more complex than that:

- there's up to 5 fields ("markers (optional), hostnames, keytype, base64-encoded key, comment")
- key can be revoked (@revoked marker)
- hostnames are patterns (`*` and `?` act as wild-cards, `!` for negation, `[]` for address with optionnal `:` for port)
- lines may be commented out
- hostnames may be stored in a hashed form (start with `|`, it seems it's the default for [some ?] Debian)

The provided example is scary:
```
        # Comments allowed at start of line
        closenet,...,192.0.2.53 1024 37 159...93 closenet.example.net
        cvs.example.net,192.0.2.10 ssh-rsa AAAA1234.....=
        # A hashed hostname
        |1|JfKTdBh7rNbXkVAQCRp4OQoPfmI=|USECr3SWf1JUPsms5AqfD5QfxkM= ssh-rsa
        AAAA1234.....=
        # A revoked key
        @revoked * ssh-rsa AAAAB5W...
        # A CA key, accepted for any host in *.mydomain.com or *.mydomain.org
        @cert-authority *.mydomain.org,*.mydomain.com ssh-rsa AAAAB5W...
```
Writing a correct parser for this file requires a bit of work. Even a "very basic" parser, like this PR, is probably useless, since it does not work for Debian (7 at least) from my experience.

**Comment by adampointer** [comment]
I agree, I had to fudge my known_hosts to get this to work as of did not like the :22. Feels like there should be a third party library for this. Should we need to reinvent the wheel here? I will have a look around and see of someone had already solved this.

**Comment by smola** [comment]
Other projects are doing their own thing: https://github.com/coreos/fleet/blob/master/ssh/known_hosts.go

It seems fleet does skip the revoked marker, which doesn't sound right. Unless there is a lightweight third-party library for this, I think we should add proper support in our code base.

**Comment by Xfennec** [comment]
If it can be of any help, I've implemented a more complete parser yesterday. It lacks wildcard support, but all other `known_hosts` "features" referenced in my previous post are supported. I think : https://github.com/Xfennec/nosee/blob/19c2994ddb72c0725337120925efff8e9382e1a2/ssh.go#L58-L132

**Comment by smola** [comment]
@Xfennec @a17n Did you check this: https://godoc.org/golang.org/x/crypto/ssh#ParseKnownHosts

**Comment by Xfennec** [comment]
@smola Of course, it's used in my code (and in your Fleet source code link, I think) but it's doing a very small part of the job.

**Comment by adampointer** [comment]
I will look to replicate the way @Xfennec has done this. We don't need to capture every edge case for this as long as of covers the majority of situations. It can always be iterated upon once merged. 

I will get cracking on this next week after the long Easter weekend. 

Thanks for everybody's input!

**Comment by peefourtee** [comment]
FYI a [recent golang.org/x/crypto/ssh/knownhosts commit](https://github.com/golang/crypto/commit/ed779e1bec0180cdfce8135ca6558067b388777b) added https://godoc.org/golang.org/x/crypto/ssh/knownhosts#New for creating a `ssh.HostKeyCallback` from knownhosts

**Comment by mcuadros** [comment]
Closed in favor of https://github.com/src-d/go-git/pull/346

**Comment by mcuadros** [comment]
Thanks everyone

**Pull request closed without merging**
