### PR TITLE
remote: use reference deltas on push when the remote server does not support offset deltas

### PR DESCRIPTION
**Pull request by bashims**

### CODE REVIEW

**Comment by mcuadros** [comment]
@balkian can you sign the DCO and add a test?

**Comment by bashims** [comment]
@mcuadros absoulutely.

**Comment by smola** [comment]
The PR looks perfect, let's see the test cases.

**Comment by bashims** [comment]
I think I have messed up the rebase/merge for this PR. I will close out this PR and submit a new one.

**Pull request closed without merging**
