### PR TITLE
plumbing: object, new Commit.Verify method

### LINKED ISSUE #605: I would like to request `git-verify-commit` support please
great library btw! 😁

### PR DESCRIPTION
**Pull request by darkowlzz**
This change adds `Verify` function to `Commit` object.
```go
Verify(armoredKeyRing string) (*openpgp.Entity, error)
```
Provided an armored key ring, it verifies the signature of the commit.

I've tried it on my local repositories passing an armored key ring and it works as expected. But couldn't write a passing test for it because when I set a custom `TreeHash` and `ParentHashes`, the commit hash becomes `0000000000000000000000000000000000000000`. Maybe I can use an existing signed commit in the fixtures, provided signing public key? Need help with the test.

Export an armored key ring:
```
$ gpg --armor --export user@example.com
```

fixes #605

### CODE REVIEW

**Comment by mcuadros** [comment]
Awesome @darkowlzz, but ... the CI is failling:
```
.. value errors.SignatureError = "hash tag doesn't match" ("openpgp: invalid signature: hash tag doesn't match")`
```

Also can use this pattern in the message commits? 
`<package>: <subpackage>, <message>`

**Comment by darkowlzz** [comment]
Alright, I've managed to write a working test to verify signature verification 😊

I don't think the test failures in travis and appveyor are related to my changes.

**Comment by mcuadros** [comment]
Its failing in TravisCI after merged it: https://travis-ci.org/src-d/go-git/jobs/306660028. Can you fix this @darkowlzz, Thanks!

**Comment by darkowlzz** [comment]
@mcuadros oh! sorry for that. I've submitted a fix in #656

**Comment by blacktop** [comment]
How do I use this?  It isn't in the gopkg.in and when I try to use `go get -u github.com/src-d/go-git/...`

I get the error:
```
package github.com/src-d/go-git: code in directory /Users/user/src/go/src/github.com/src-d/go-git expects import "gopkg.in/src-d/go-git.v4"
```

**Comment by ferhatelmas** [comment]
@blacktop See #380, please.

**Comment by blacktop** [comment]
Thank you! with the rise of `go dep` it seems like gopkg is falling out of favor.

**Comment by orirawlings** [comment]
@blacktop So far the changes have only been integrated to the `master` branch. Once another rc or official version is integrated to the `v4` branch it will be available via `go get -u gopkg.in/src-d/go-git.v4`

**Pull request merged**
