### PR TITLE
added credentials provider for basic auth

### LINKED ISSUE #350: AuthMethod in http/common.go needs to export setAuth
right now the setAuth is not exported. It should be SetAuth. Otherwise, there's no way for a consumer to apply basic auth (e.g. ask for user/pass) when it's needed and instead they need to do it when the Auth is set on the Config which means you may ask for a user/pass before you know if an endpoint actually reuires auth.

Making the SetAuth exported is a quick fix so consumers can just implement the interface instead of using the built-in BasicAuth.

A better route would probably be to add a callback for grabbing the user/pass.

### PR DESCRIPTION
**Pull request by jdoklovic**
Fixes #350

### CODE REVIEW

**Comment by bzz** [comment]
Number of CI failures on Win might be related to #369 

Ping @smola @alcortesm @mcuadros for a review

**Comment by jdoklovic** [comment]
I'm not sure how those failures got introduced unless windows tests were failing on master when i branched.
My changes are obviously very small and don't have anything to do with the failures listed

**Comment by jdoklovic** [comment]
@smola @mcuadros any suggestions on how to fix this up and get it merged? I need this change for a CLI tool i'm building...

**Comment by smola** [comment]
@bzz Please, just ignore Windows failures, except for PR fixing stuff on Windows.

**Comment by smola** [comment]
Closing. See: https://github.com/src-d/go-git/issues/350#issuecomment-300096008

**Pull request closed without merging**
