### PR TITLE
Adds support to open local repositories and to use file-based object storage

### PR DESCRIPTION
**Pull request by alcortesm**
This patch addresses https://github.com/src-d/go-git/issues/51 and https://github.com/src-d/go-git/issues/19.

Local repositories can now be opened by using the `NewRepositoryFromFS(path string)` repository constructor.

The default storage for such repositories is just a proxy to the original repository, meaning no git objects are stored on memory and all queries to the repository are resolved by accessing the original repository packfile and idx file in its ".git" directory.

### CODE REVIEW

**Comment by alcortesm** [comment]
Please, don't merge yet, i just realize support for processing REF deltas when creating the index from raw packfiles is not supported yet. Give a few days to finish this.

**Comment by themihai** [comment]
@alcortesm  Could NewRepositoryFromFS could accept an interface instead of a file path?  That way we can use a remote service (e.g. amazon S3) as local storage 

_Not affiliated with the project._

**Comment by alcortesm** [comment]
Ready to merge, IMHO.

**Comment by alcortesm** [comment]
Got some comments from @mcuadros IRL, implementing them right now.

**Pull request merged**
