### PR TITLE
Check if list of files is empty.

### PR DESCRIPTION
**Pull request by kuba--**
Signed-off-by: kuba-- <kuba@sourced.tech>

Closes https://github.com/src-d/go-git/issues/877

### CODE REVIEW

**Comment by mcuadros** [comment]
Can we add a test for this?

**Comment by kuba--** [comment]
I'll try to generate some fake `know_hosts`  files. We'll see how it goes

**Comment by kuba--** [comment]
@mcuadros - I've added `TestNewKnownHostsCallback` which mocks a `known_hosts` file with `github` host.

**Comment by kuba--** [comment]
rebased

**Pull request closed without merging**
