### PR TITLE
Worktree: improve build index performance.

### PR DESCRIPTION
**Pull request by orisano**
ref: #1170

### CODE REVIEW

**Comment by orisano** [comment]
name          old time/op    new time/op    delta
PlainClone-4      605s ± 4%      249s ± 7%  -58.91%  (p=0.008 n=5+5)

name          old alloc/op   new alloc/op   delta
PlainClone-4    64.9GB ± 0%    56.1GB ± 0%  -13.48%  (p=0.008 n=5+5)

name          old allocs/op  new allocs/op  delta
PlainClone-4      117M ± 0%      118M ± 0%   +0.57%  (p=0.008 n=5+5)

**Comment by jfontan** [comment]
I believe you can also add the changes in `storage/filesystem/index.go` from #1170. These should improve speed even more.

**Comment by orisano** [comment]
Added!

**Comment by jfontan** [comment]
@orisano Thanks!

@mcuadros it LGTM

**Pull request merged**
